// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pilldue.Data;

#nullable disable

namespace Pilldue.Data.Migrations
{
    [DbContext(typeof(PilldueDbContext))]
    partial class PilldueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Pilldue.Business.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStockPills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyDosagePills")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageSizePills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrescribedPackageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrescriptionDurationMonths")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PrescriptionStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RefillDayOfMonthOverride")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("medications", (string)null);
                });

            modelBuilder.Entity("Pilldue.Business.RefillEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId");

                    b.ToTable("refill_events", (string)null);
                });

            modelBuilder.Entity("Pilldue.Business.SkipDoseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PillsReturned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId");

                    b.ToTable("skip_dose_events", (string)null);
                });

            modelBuilder.Entity("Pilldue.Business.RefillEvent", b =>
                {
                    b.HasOne("Pilldue.Business.Medication", null)
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pilldue.Business.SkipDoseEvent", b =>
                {
                    b.HasOne("Pilldue.Business.Medication", null)
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
